blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Code With CLI
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline-with-cli&ssr=false#review-details
      about: Enjoying Roo Code With CLI? Leave a review here!
